name: Simple pipeline to build firmware, flash DUT, and run tests
on: [push]
env:
  LAGER_GATEWAY: blissful-badger

jobs:
  build_flash_and_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build
        uses: docker://lagerdata/devenv-cortexm-minimal
        with:
          entrypoint: /usr/local/bin/lager
          args: exec build

      - name: Connect to debugger
        uses: docker://lagerdata/lager-cli:v0.1.45
        env:
          LAGER_SECRET_TOKEN: ${{ secrets.AKBAR_SECRET_TOKEN }}
        with:
          entrypoint: /usr/local/bin/lager
          args: connect --device nrf52 --force

      - name: Flash and run
        uses: docker://lagerdata/lager-cli:v0.1.45
        env:
          LAGER_SECRET_TOKEN: ${{ secrets.AKBAR_SECRET_TOKEN }}
        with:
          entrypoint: /usr/local/bin/lager
          args: testrun --serial-device /dev/ttyACM0 --hexfile _build/unit-tests/test-suites/test-example/test-example.hex

      - name: Copy hex into LED test folder
        run: cp _build/app/app.hex system-tests/led_test

      - name: LED Test
        uses: docker://lagerdata/lager-cli:v0.1.45
        env:
          LAGER_SECRET_TOKEN: ${{ secrets.AKBAR_SECRET_TOKEN }}
        with:
          entrypoint: /usr/local/bin/lager
          args: python system-tests/led_test
